name: geophysics_base
channels:
  - conda-forge #manually added, maybe defaults channel is enough?
  - defaults
dependencies:
  - python
  - pip
  - openpyxl
  - pyyaml
  - jupyter
  - numpy
  - matplotlib
  - numba
  - pandas
  - geopandas
  - scikit-learn
  - tensorflow
  - triangle
  - pykrige
  - keras
  - numba
